# it is not really python, but there is no R support on Travis CI yet
language: python

# environment variables
env:
  - R_LIBS_USER=~/R

# install dependencies
install:
  - sudo apt-add-repository -y 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends r-base-dev r-cran-xml r-cran-rcurl qpdf texinfo texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - R -e '.libPaths(); sessionInfo()'
  - git clone https://github.com/krlmlr/crant.git ~/crant

# run tests
script:
  - ~/crant/rant
