# Sample .travis.yml for R projects.
#
# See README.md for instructions.

language: c
# To build on OSX, switch the previous line to
# language: objective-c
script: ./travis-tool.sh run_tests
env:
  global:
    - WARNINGS_ARE_ERRORS=1

before_script:
  - ./travis-tool.sh dump_sysinfo
after_success:
  - ./travis-tool.sh dump_logs_by_extension out
after_failure:
  - ./travis-tool.sh dump_logs
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh r_binary_install Rcpp RUnit inline highlight XML
  - ./travis-tool.sh install_github hadley/testthat
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_deps
notifications:
  email:
    on_success: change
    on_failure: change
